version: "3.9"

services:
    testausapis:
        build:
            context: .
            network: host
        image: ghcr.io/testausserveri/testausapis
        restart: unless-stopped
        depends_on:
            - testausapis_mongo
        env_file:
            - .env
        ports:
            - "8140:8080"
        links:
            - testausapis_mongo
        volumes:
            - ./media:/usr/src/app/media
    testausapis_mongo:
        container_name: testausapis_mongo
        restart: unless-stopped
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - "27017:27017"
