version: "3.9"

services:
    testausapis:
        build:
            context: .
        image: ghcr.io/testausserveri/testausapis
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "8140:8080"
        links:
            - testausapis_mongo
    testausapis_mongo:
        container_name: testausapis_mongo
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - '27017:27017'
