version: "3.9"

services:
    app:
        build:
            context: .
        image: ghcr.io/testausserveri/testausapis
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "8140:8080"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - '27018:27017'