version: "3.9"

services:
    app:
        build:
            context: .
        image: ghcr.io/testausserveri/testausapis
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "8140:8080"